controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_revolute_1
      - arm_slider_1
      - arm_revolute_2
      - arm_slider_2
      - arm_revolute_3
      - arm_slider_3
      - arm_revolute_4
      - arm_slider_4

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    #TODO Placeholder values for joint trajectory controller
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    interpolate_from_desired_state: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03

velocity_controller:
  ros__parameters:
    joints:
      - canvas_revolute