@startuml PenVisualizerClass

class Pen{
    -tf2_listener_ : std::shared_ptr<tf2_ros::TransformListener>
    -tf2_buffer_ : std::unique_ptr<tf2_ros::Buffer>
    -last_transform_stamp_ : rclcpp::Time 
    -state_ : bool
    -frame_id_ : std::string
    -canvas_frame_id_ : std::string
    -logger_ : rclcpp::Logger
    -clock_ : rclcpp::Clock::SharedPtr
    +set_state(bool state)
    +generate_marker(unsigned int marker_count) : std::optional<visualization_msgs/msg/Marker>
}

class PenVisualizer{
    -pen_array_ : std::Array<Pen>
    -marker_count_ : unsigned int
    -timer_callback()
    -state_callback(int pen, std_msgs/msg/Bool msg)
    -publish_marker(visualization_msgs/msg/Marker marker)
    .. Parameters ..
    +canvas_frame_id
    +pen_frame_prefix
    +pen_state_topic_prefix
    +update_frequency
    .. Topics ..
    -<<Timer>> timer_
    -<<Subscriber>> state_sub_array_ : std::Array<std_msgs/msg/Bool>
    -<<Publisher>> marker_pub_ : visualization_msgs/msg/Marker
}

Pen --* "4..4" PenVisualizer
@enduml

@startuml PenVisualizerActivity
start
:timer_callback triggered;
partition "generate_marker" {
    if (Pen State?) then (down)
        if (try Lookup transform from pen frame to canvas frame) then (success)
            if (transform stamp == last transform stamp?) then (true)
                :log INFO "Duplicate Transform";
                :return nullopt;
            else(false)
                :Update last transform stamp;
                if(Current marker active?) then (true)
                else (false)
                    :Create new marker without points;
                    :Set active marker to true;
                endif
                :Update marker timestamp;
                :Generate point;
                :Add point to current marker;
                :log INFO "Updating marker <id> for <frame_id>";
                :return current marker;
            endif
        else (catch)
            :log WARN "Bad Transform Lookup";
            :return nullopt;
        endif
        else (up)
            if(Current marker active?) then (true)
                :Set active marker to false;
                :log INFO "Finished marker <id> for <frame_id>";
                :Increment marker id;
                :return current marker;
            else (false)
                :return nullopt;
            endif
        endif
    }
    if (Optional has value) then (true)
        :Publish Marker;
    else (false)
    endif
stop
@enduml
