@startuml PenVisualizerClass

class Pen{
    -tf2_listener_ : std::shared_ptr<tf2_ros::TransformListener>
    -tf2_buffer_ : std::unique_ptr<tf2_ros::Buffer>
    -last_transform_stamp_ : rclcpp::Time 
    -frame_id_ : std::string
    -canvas_frame_id_ : std::string
    -logger_ : rclcpp::Logger
    +generate_marker(unsigned int marker_count) : std::optional<visualization_msgs/msg/Marker>
}

class PenVisualizer{
    -pen_array_ : std::Array<Pen>
    -marker_count_ : unsigned int
    -state_callback(int id, std_msgs/msg/Bool msg)
    -publish_marker(visualization_msgs/msg/Marker marker)
    .. Parameters ..
    +canvas_frame_id
    +pen_frame_prefix
    +pen_state_topic_prefix
    .. Topics ..
    -<<Subscriber>> state_sub_array_ : std::Array<std_msgs/msg/Bool>
    -<<Publisher>> marker_pub_ : visualization_msgs/msg/Marker
}

Pen --* "4..4" PenVisualizer
@enduml

@startuml PenVisualizerActivity
start
:state_callback triggered;
if (Pen State?) then (down)
    partition "generate_marker" {
        if (try Lookup transform from pen frame to canvas frame) then (success)
            if (transform stamp == last transform stamp?) then (true)
                :log INFO "Duplicate Transform";
                :return nullopt;
            else(false)
                :Generate marker;
                :Update last transform stamp;
                :return marker;
            endif
        else (catch)
            :log WARN "Bad Transform Lookup";
            :return nullopt;
        endif
    }
    if (Optional has value) then (true)
        :log INFO "Publishing Marker <number>";
        :Increment marker count;
        :Publish Marker;
    else (false)
    endif
else (up)
endif
stop
@enduml
